# Remove the version directive as it's now obsolete
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - trimsee-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - trimsee-network

networks:
  trimsee-network:
    driver: bridge