version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: trimsee-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - trimsee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  backend:
    container_name: trimsee-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    environment:
      - PORT=3200
      - DB_URI=${DB_URI:-mongodb://mongodb:27017/trimsee}
      - BASE=http://localhost:3200
      - NODE_ENV=development
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - trimsee-network
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3200/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  frontend:
    container_name: trimsee-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_BASE_URL=http://localhost:3200
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - trimsee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  trimsee-network:
    driver: bridge

volumes:
  mongodb_data:
