version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./server
    container_name: backend
    ports:
      - "3200:3200"
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017/urlshortener
      - BASE=http://localhost:3200
    restart: always

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BASE_URL=http://localhost:3200
    stdin_open: true
    tty: true
    restart: always

volumes:
  mongo-data:
