version: '3.8'

services:
  backend:
    container_name: trimsee-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    env_file:
      - ./server/.env
    working_dir: /app
    volumes:
      - ./server:/app
      # - /app/node_modules
    networks:
      - trimsee-network

  frontend:
    container_name: trimsee-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    working_dir: /app
    volumes:
      - ./client:/app
      # - /app/node_modules
    depends_on:
      - backend
    networks:
      - trimsee-network

networks:
  trimsee-network:
    driver: bridge
