version: '3.8'

services:
  backend:
    container_name: trimsee-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    environment:
      - PORT=3200
      - DB_URI=mongodb+srv://nikhanjmridul:XcRsInwe9rfoVAtm@cluster0.o59qiro.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - BASE=http://localhost:3200
      - NODE_ENV=development
      - DEBUG=express:*,mongodb:*
      - NODE_OPTIONS=--trace-warnings
    working_dir: /app
    networks:
      - trimsee-network
    restart: unless-stopped

  frontend:
    container_name: trimsee-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_BASE_URL=http://localhost:3200
    working_dir: /app
    depends_on:
      - backend
    networks:
      - trimsee-network
    restart: unless-stopped

networks:
  trimsee-network:
    driver: bridge
