version: '3.8'

services:
  backend:
    container_name: trimsee-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    env_file:
      - ./server/.env
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - trimsee-network
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  frontend:
    container_name: trimsee-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - trimsee-network
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

networks:
  trimsee-network:
    driver: bridge
