version: '3.8'

services:
  backend:
    container_name: trimsee-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    environment:
      - PORT=3200
      - DB_URI=mongodb+srv://nikhanjmridul:XcRsInwe9rfoVAtm@cluster0.o59qiro.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - BASE=http://localhost:3200
      - NODE_ENV=production
      - DEBUG=express:*,mongodb:*
      - NODE_OPTIONS=--max-old-space-size=8192
    working_dir: /app
    networks:
      - trimsee-network
    restart: unless-stopped
    oom_kill_disable: true
    mem_swappiness: 60
    memswap_limit: -1
    mem_reservation: 256M
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    container_name: trimsee-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REACT_APP_BASE_URL=http://localhost:3200
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=8192
    working_dir: /app
    depends_on:
      - backend
    networks:
      - trimsee-network
    restart: unless-stopped
    oom_kill_disable: true
    mem_swappiness: 60
    memswap_limit: -1
    mem_reservation: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 45s
      timeout: 30s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  trimsee-network:
    driver: bridge
